"""add campos agencia/anunciante

Revision ID: 52222b71a2cb
Revises: 
Create Date: 2025-10-13 16:55:40.541266

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '52222b71a2cb'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agencias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome_agencia', sa.String(), nullable=False),
    sa.Column('razao_social_agencia', sa.String(), nullable=True),
    sa.Column('cnpj_agencia', sa.String(), nullable=False),
    sa.Column('uf_agencia', sa.String(), nullable=True),
    sa.Column('executivo', sa.String(), nullable=False),
    sa.Column('email_agencia', sa.String(), nullable=True),
    sa.Column('data_cadastro', sa.String(), nullable=True),
    sa.Column('grupo_empresarial', sa.String(), nullable=True),
    sa.Column('codinome', sa.String(), nullable=True),
    sa.Column('site', sa.String(), nullable=True),
    sa.Column('linkedin', sa.String(), nullable=True),
    sa.Column('instagram', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cnpj_agencia')
    )
    with op.batch_alter_table('agencias', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agencias_codinome'), ['codinome'], unique=True)

    op.create_table('anunciantes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome_anunciante', sa.String(), nullable=False),
    sa.Column('razao_social_anunciante', sa.String(), nullable=True),
    sa.Column('cnpj_anunciante', sa.String(), nullable=False),
    sa.Column('uf_cliente', sa.String(), nullable=True),
    sa.Column('executivo', sa.String(), nullable=False),
    sa.Column('email_anunciante', sa.String(), nullable=True),
    sa.Column('data_cadastro', sa.String(), nullable=True),
    sa.Column('grupo_empresarial', sa.String(), nullable=True),
    sa.Column('codinome', sa.String(), nullable=True),
    sa.Column('site', sa.String(), nullable=True),
    sa.Column('linkedin', sa.String(), nullable=True),
    sa.Column('instagram', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cnpj_anunciante')
    )
    with op.batch_alter_table('anunciantes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_anunciantes_codinome'), ['codinome'], unique=True)

    op.create_table('pis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero_pi', sa.String(), nullable=False),
    sa.Column('numero_pi_matriz', sa.String(), nullable=True),
    sa.Column('numero_pi_normal', sa.String(), nullable=True),
    sa.Column('tipo_pi', sa.String(), nullable=False),
    sa.Column('nome_anunciante', sa.String(), nullable=True),
    sa.Column('razao_social_anunciante', sa.String(), nullable=True),
    sa.Column('cnpj_anunciante', sa.String(), nullable=True),
    sa.Column('uf_cliente', sa.String(), nullable=True),
    sa.Column('nome_agencia', sa.String(), nullable=True),
    sa.Column('razao_social_agencia', sa.String(), nullable=True),
    sa.Column('cnpj_agencia', sa.String(), nullable=True),
    sa.Column('uf_agencia', sa.String(), nullable=True),
    sa.Column('executivo', sa.String(), nullable=True),
    sa.Column('diretoria', sa.String(), nullable=True),
    sa.Column('nome_campanha', sa.String(), nullable=True),
    sa.Column('mes_venda', sa.String(), nullable=True),
    sa.Column('dia_venda', sa.String(), nullable=True),
    sa.Column('canal', sa.String(), nullable=True),
    sa.Column('perfil', sa.String(), nullable=True),
    sa.Column('subperfil', sa.String(), nullable=True),
    sa.Column('valor_bruto', sa.Float(), nullable=True),
    sa.Column('valor_liquido', sa.Float(), nullable=True),
    sa.Column('vencimento', sa.Date(), nullable=True),
    sa.Column('data_emissao', sa.Date(), nullable=True),
    sa.Column('observacoes', sa.String(), nullable=True),
    sa.Column('agencia_id', sa.Integer(), nullable=True),
    sa.Column('anunciante_id', sa.Integer(), nullable=True),
    sa.Column('eh_matriz', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['agencia_id'], ['agencias.id'], ),
    sa.ForeignKeyConstraint(['anunciante_id'], ['anunciantes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero_pi')
    )
    op.create_table('produtos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('pi_id', sa.Integer(), nullable=True),
    sa.Column('descricao', sa.String(), nullable=True),
    sa.Column('categoria', sa.String(), nullable=True),
    sa.Column('modalidade_preco', sa.String(), nullable=True),
    sa.Column('base_segundos', sa.Integer(), nullable=True),
    sa.Column('unidade_rotulo', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['pi_id'], ['pis.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('veiculacoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('produto_id', sa.Integer(), nullable=True),
    sa.Column('pi_id', sa.Integer(), nullable=True),
    sa.Column('canal', sa.String(), nullable=True),
    sa.Column('formato', sa.String(), nullable=True),
    sa.Column('data_inicio', sa.String(), nullable=True),
    sa.Column('data_fim', sa.String(), nullable=True),
    sa.Column('quantidade', sa.Integer(), nullable=True),
    sa.Column('valor_bruto', sa.Float(), nullable=True),
    sa.Column('desconto', sa.Float(), nullable=True),
    sa.Column('valor_liquido', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['pi_id'], ['pis.id'], ),
    sa.ForeignKeyConstraint(['produto_id'], ['produtos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('entregas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data_entrega', sa.Date(), nullable=False),
    sa.Column('foi_entregue', sa.String(), nullable=True),
    sa.Column('motivo', sa.String(), nullable=True),
    sa.Column('veiculacao_id', sa.Integer(), nullable=True),
    sa.Column('pi_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['pi_id'], ['pis.id'], ),
    sa.ForeignKeyConstraint(['veiculacao_id'], ['veiculacoes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('entregas')
    op.drop_table('veiculacoes')
    op.drop_table('produtos')
    op.drop_table('pis')
    with op.batch_alter_table('anunciantes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_anunciantes_codinome'))

    op.drop_table('anunciantes')
    with op.batch_alter_table('agencias', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agencias_codinome'))

    op.drop_table('agencias')
    # ### end Alembic commands ###
